server:
  port: 8890

spring:
  application:
    name: auth-api
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 1000
        order_inserts: true
        order_updates: true
    open-in-view: false

logging:
  level:
    root: info
    me.lozm: debug

jwt:
  secret: hashing-jwt-token-secret-key-test
  expiration-time: 18000
  token-prefix: Bearer
  header-string: Authorization

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
  ConnectTimeout: 1000
  MaxTotalConnections: 300
  MaxConnectionsPerHost: 100
  retryableStatusCodes: 500

eureka:
  client:
    enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: false
      log-format: '#%(connectionId) | %(executionTime)ms | %(category) | %(sql)'

zuul:
  igoredServices: '*'
  routes:
    community-api:
      path: /community-api/**
      serviceId: community-api
      stripPrefix: true
  retryable: true
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: auth-api
