### 사용자 추가 > 관리자
POST {{host}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibmFtZSI6IuyCrOyaqeyekCIsImlkIjozLCJleHAiOjE2MjkyMTUyNjIsImlhdCI6MTYyOTE5NzI2Mn0.1w5nwrHjEb1ePZTwNmV7hfY2rTYNxVNPVgani01kYt4D61o_aK1KO0zY99qdsoFxWqAJmH4E8tI2j0pxOKF4QQ

{
  "name": "관리자",
  "identifier": "admin",
  "password": "asdfasdf1234",
  "type": "ADMIN"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is not 200");
  client.global.set("userId", response.body.id);
});
%}

### 사용자 추가 > 매니저
POST {{host}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibmFtZSI6IuyCrOyaqeyekCIsImlkIjozLCJleHAiOjE2MjkyMTUyNjIsImlhdCI6MTYyOTE5NzI2Mn0.1w5nwrHjEb1ePZTwNmV7hfY2rTYNxVNPVgani01kYt4D61o_aK1KO0zY99qdsoFxWqAJmH4E8tI2j0pxOKF4QQ

{
  "name": "매니저",
  "identifier": "manager",
  "password": "asdfasdf1234",
  "type": "USER"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is not 200");
  client.global.set("userId", response.body.id);
});
%}

### 사용자 추가 > 일반 사용자
POST {{host}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibmFtZSI6IuyCrOyaqeyekCIsImlkIjozLCJleHAiOjE2MjkyMTUyNjIsImlhdCI6MTYyOTE5NzI2Mn0.1w5nwrHjEb1ePZTwNmV7hfY2rTYNxVNPVgani01kYt4D61o_aK1KO0zY99qdsoFxWqAJmH4E8tI2j0pxOKF4QQ

{
  "name": "일반 사용자",
  "identifier": "user",
  "password": "asdfasdf1234",
  "type": "USER"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is not 200");
  client.global.set("userId", response.body.id);
});
%}

### 사용자 목록 조회
GET {{host}}/user/userType/ALL
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibmFtZSI6IuyCrOyaqeyekCIsImlkIjozLCJleHAiOjE2MjkyMTUyNjIsImlhdCI6MTYyOTE5NzI2Mn0.1w5nwrHjEb1ePZTwNmV7hfY2rTYNxVNPVgani01kYt4D61o_aK1KO0zY99qdsoFxWqAJmH4E8tI2j0pxOKF4QQ

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is not 200");
});
%}

### 사용자 상세 조회
GET {{host}}/user/{{userId}}
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibmFtZSI6IuyCrOyaqeyekCIsImlkIjozLCJleHAiOjE2MjkyMTUyNjIsImlhdCI6MTYyOTE5NzI2Mn0.1w5nwrHjEb1ePZTwNmV7hfY2rTYNxVNPVgani01kYt4D61o_aK1KO0zY99qdsoFxWqAJmH4E8tI2j0pxOKF4QQ

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is not 200");
});
%}

### 사용자 수정
PUT {{host}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibmFtZSI6IuyCrOyaqeyekCIsImlkIjozLCJleHAiOjE2MjkyMTUyNjIsImlhdCI6MTYyOTE5NzI2Mn0.1w5nwrHjEb1ePZTwNmV7hfY2rTYNxVNPVgani01kYt4D61o_aK1KO0zY99qdsoFxWqAJmH4E8tI2j0pxOKF4QQ

{
  "id": "{{userId}}",
  "name": "변경된 사용자",
  "password": "asdfasdf1234asdf!",
  "type": "USER"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is not 200");
});
%}

### 사용자 삭제
DELETE {{host}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibmFtZSI6IuyCrOyaqeyekCIsImlkIjozLCJleHAiOjE2MjkyMTUyNjIsImlhdCI6MTYyOTE5NzI2Mn0.1w5nwrHjEb1ePZTwNmV7hfY2rTYNxVNPVgani01kYt4D61o_aK1KO0zY99qdsoFxWqAJmH4E8tI2j0pxOKF4QQ

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status == 200, "Response status is not 200");
});
%}
